### ISSUE TITLE
question about write results

### ISSUE THREAD

**Issue by boxerab** [kkourt/aio-test#2]
When I run the test program for writes, I always get only a single entry:
```
$ ./aio-test  -f FILE  -w 100 | grep -o 'in_flight:[^ ]\+' | sort -V | uniq -c

   3125 in_flight:0
```

For reads I do get concurrency. Any ideas on why this is the case? This is with a quite new version of the kernel.

Thanks.

**Comment by kkourt** [comment]
Hm... not sure the kernel implements concurrency for writes (even new versions).
It's also worth mentioning that aio has been surpassed by `io_uring` which is a much better interface.
See: https://github.com/axboe/liburing

**Comment by boxerab** [comment]
Thanks. This result is from my laptop with spinning rust disk. I also tried on my desktop with `5.4.0-42` kernel and PCI 4 SSD, and I get very nice write concurrency. 

Thanks for the `io-uring` link, I was following this, but didn't  know it was merged.
